### PR TITLE
Dock / status bar rochade

### PR DESCRIPTION
**Pull request by marckrenn**
**Changes**
- Removed permanent Dock Icon
- Re-enabled Menu Bar Menu, which now uses the `☀` symbol as an icon and holds a `Quit` action. I consider this is as a complete MVP UI. 
- Cranked up the sync-rate to .1s, which might affect CPU usage negatively, but it's still fine for me personally.

**Please be aware**
- I'm not a coder
- I have no idea what I'm doing `¯\_(ツ)_/¯`
- No prior experience in Objective-C nor macOS development

### CODE REVIEW

**Comment by marckrenn** [comment]
By the way, I'd love to see a complete Swift rewrite of this deamon using DDC control. Hell, I think people would then even pay for this. I sure as hell would.

**Comment by baragona** [comment]
I merged this into master, the changes seem good! Thanks for your help.
Please be aware:
- You are now a coder

**Comment by borekb** [comment]
@ojotoxy Hi, should this be included in the app files linked from README, i.e., https://www.dropbox.com/s/qit5awr1dop2fei/Brightness.app.zip?dl=0? I'm only seeing the app running in Dock, not in menu bar.

Thanks for the awesome app BTW!

**Comment by lacek** [comment]
@borekb The app linked in README was built prior to this PR (judging from the timestamps of the files).

If you have xcode installed on your Mac, you can try to build yourself:

```sh
git clone https://github.com/ojotoxy/Brightness
cd Brightness/Brightness
xcodebuild build
```

The compiled app can then be found in `build/Release` directory.

**Comment by borekb** [comment]
I've never used xcode and when I try the above, I get

```
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
```

Is there a built file in someone's Dropbox somewhere?

**Comment by baragona** [comment]
I updated the file on dropbox just now, can you give it a try?

**Comment by borekb** [comment]
That worked, thank you!

**Comment by lacek** [comment]
@ojotoxy Thanks for the great work. I think it would even be better if you [create a release in GitHub](https://help.github.com/articles/creating-releases/) with the build as attachment. This will help user to refer to the release when they are reporting issue. It also save your own Dropbox traffic quota.

**Comment by baragona** [comment]
Good thinking! Released.

**Pull request merged**
